package com.ti.ble.common;

import java.util.HashMap;
import java.util.Map;

public class BluetoothGATTDefines
{
  public static final Map<Integer, String> gattErrorCodeStrings = new HashMap();
  public static final Map<Integer, String> manufacturerIDStrings;
  
  static
  {
    gattErrorCodeStrings.put(Integer.valueOf(0), "GATT Success");
    gattErrorCodeStrings.put(Integer.valueOf(2), "GATT Read Not Permitted");
    gattErrorCodeStrings.put(Integer.valueOf(3), "GATT Write Not Permitted");
    gattErrorCodeStrings.put(Integer.valueOf(5), "GATT Insufficient Authentication");
    gattErrorCodeStrings.put(Integer.valueOf(6), "GATT Request Not Supported");
    gattErrorCodeStrings.put(Integer.valueOf(7), "GATT Invalid Offset");
    gattErrorCodeStrings.put(Integer.valueOf(13), "GATT Invalid Attribute Length");
    gattErrorCodeStrings.put(Integer.valueOf(15), "GATT Insufficient Encryption");
    gattErrorCodeStrings.put(Integer.valueOf(143), "GATT Connection Congested");
    gattErrorCodeStrings.put(Integer.valueOf(257), "GATT Failure");
    manufacturerIDStrings = new HashMap();
    manufacturerIDStrings.put(Integer.valueOf(0), "Ericsson Technology Licensing");
    manufacturerIDStrings.put(Integer.valueOf(1), "Nokia Mobile Phones");
    manufacturerIDStrings.put(Integer.valueOf(2), "Intel Corp.");
    manufacturerIDStrings.put(Integer.valueOf(3), "IBM Corp.");
    manufacturerIDStrings.put(Integer.valueOf(4), "Toshiba Corp.");
    manufacturerIDStrings.put(Integer.valueOf(5), "3Com");
    manufacturerIDStrings.put(Integer.valueOf(6), "Microsoft");
    manufacturerIDStrings.put(Integer.valueOf(7), "Lucent");
    manufacturerIDStrings.put(Integer.valueOf(8), "Motorola");
    manufacturerIDStrings.put(Integer.valueOf(9), "Infineon Technologies AG");
    manufacturerIDStrings.put(Integer.valueOf(10), "Cambridge Silicon Radio");
    manufacturerIDStrings.put(Integer.valueOf(11), "Silicon Wave");
    manufacturerIDStrings.put(Integer.valueOf(12), "Digianswer A/S");
    manufacturerIDStrings.put(Integer.valueOf(13), "Texas Instruments Inc.");
    manufacturerIDStrings.put(Integer.valueOf(14), "Ceva, Inc. (formerly Parthus Technologies, Inc.)");
    manufacturerIDStrings.put(Integer.valueOf(15), "Broadcom Corporation");
    manufacturerIDStrings.put(Integer.valueOf(16), "Mitel Semiconductor");
    manufacturerIDStrings.put(Integer.valueOf(17), "Widcomm, Inc");
    manufacturerIDStrings.put(Integer.valueOf(18), "Zeevo, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(19), "Atmel Corporation");
    manufacturerIDStrings.put(Integer.valueOf(20), "Mitsubishi Electric Corporation");
    manufacturerIDStrings.put(Integer.valueOf(21), "RTX Telecom A/S");
    manufacturerIDStrings.put(Integer.valueOf(22), "KC Technology Inc.");
    manufacturerIDStrings.put(Integer.valueOf(23), "NewLogic");
    manufacturerIDStrings.put(Integer.valueOf(24), "Transilica, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(25), "Rohde & Schwarz GmbH & Co. KG");
    manufacturerIDStrings.put(Integer.valueOf(26), "TTPCom Limited");
    manufacturerIDStrings.put(Integer.valueOf(27), "Signia Technologies, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(28), "Conexant Systems Inc.");
    manufacturerIDStrings.put(Integer.valueOf(29), "Qualcomm");
    manufacturerIDStrings.put(Integer.valueOf(30), "Inventel");
    manufacturerIDStrings.put(Integer.valueOf(31), "AVM Berlin");
    manufacturerIDStrings.put(Integer.valueOf(32), "BandSpeed, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(33), "Mansella Ltd");
    manufacturerIDStrings.put(Integer.valueOf(34), "NEC Corporation");
    manufacturerIDStrings.put(Integer.valueOf(35), "WavePlus Technology Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(36), "Alcatel");
    manufacturerIDStrings.put(Integer.valueOf(37), "NXP Semiconductors (formerly Philips Semiconductors)");
    manufacturerIDStrings.put(Integer.valueOf(38), "C Technologies");
    manufacturerIDStrings.put(Integer.valueOf(39), "Open Interface");
    manufacturerIDStrings.put(Integer.valueOf(40), "R F Micro Devices");
    manufacturerIDStrings.put(Integer.valueOf(41), "Hitachi Ltd");
    manufacturerIDStrings.put(Integer.valueOf(42), "Symbol Technologies, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(43), "Tenovis");
    manufacturerIDStrings.put(Integer.valueOf(44), "Macronix International Co. Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(45), "GCT Semiconductor");
    manufacturerIDStrings.put(Integer.valueOf(46), "Norwood Systems");
    manufacturerIDStrings.put(Integer.valueOf(47), "MewTel Technology Inc.");
    manufacturerIDStrings.put(Integer.valueOf(48), "ST Microelectronics");
    manufacturerIDStrings.put(Integer.valueOf(49), "Synopsys, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(50), "Red-M (Communications) Ltd");
    manufacturerIDStrings.put(Integer.valueOf(51), "Commil Ltd");
    manufacturerIDStrings.put(Integer.valueOf(52), "Computer Access Technology Corporation (CATC)");
    manufacturerIDStrings.put(Integer.valueOf(53), "Eclipse (HQ Espana) S.L.");
    manufacturerIDStrings.put(Integer.valueOf(54), "Renesas Electronics Corporation");
    manufacturerIDStrings.put(Integer.valueOf(55), "Mobilian Corporation");
    manufacturerIDStrings.put(Integer.valueOf(56), "Terax");
    manufacturerIDStrings.put(Integer.valueOf(57), "Integrated System Solution Corp.");
    manufacturerIDStrings.put(Integer.valueOf(58), "Matsushita Electric Industrial Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(59), "Gennum Corporation");
    manufacturerIDStrings.put(Integer.valueOf(60), "BlackBerry Limited (formerly Research In Motion)");
    manufacturerIDStrings.put(Integer.valueOf(61), "IPextreme, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(62), "Systems and Chips, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(63), "Bluetooth SIG, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(64), "Seiko Epson Corporation");
    manufacturerIDStrings.put(Integer.valueOf(65), "Integrated Silicon Solution Taiwan, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(66), "CONWISE Technology Corporation Ltd");
    manufacturerIDStrings.put(Integer.valueOf(67), "PARROT SA");
    manufacturerIDStrings.put(Integer.valueOf(68), "Socket Mobile");
    manufacturerIDStrings.put(Integer.valueOf(69), "Atheros Communications, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(70), "MediaTek, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(71), "Bluegiga");
    manufacturerIDStrings.put(Integer.valueOf(72), "Marvell Technology Group Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(73), "3DSP Corporation");
    manufacturerIDStrings.put(Integer.valueOf(74), "Accel Semiconductor Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(75), "Continental Automotive Systems");
    manufacturerIDStrings.put(Integer.valueOf(76), "Apple, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(77), "Staccato Communications, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(78), "Avago Technologies");
    manufacturerIDStrings.put(Integer.valueOf(79), "APT Licensing Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(80), "SiRF Technology");
    manufacturerIDStrings.put(Integer.valueOf(81), "Tzero Technologies, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(82), "J&M Corporation");
    manufacturerIDStrings.put(Integer.valueOf(83), "Free2move AB");
    manufacturerIDStrings.put(Integer.valueOf(84), "3DiJoy Corporation");
    manufacturerIDStrings.put(Integer.valueOf(85), "Plantronics, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(86), "Sony Ericsson Mobile Communications");
    manufacturerIDStrings.put(Integer.valueOf(87), "Harman International Industries, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(88), "Vizio, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(89), "Nordic Semiconductor ASA");
    manufacturerIDStrings.put(Integer.valueOf(90), "EM Microelectronic-Marin SA");
    manufacturerIDStrings.put(Integer.valueOf(91), "Ralink Technology Corporation");
    manufacturerIDStrings.put(Integer.valueOf(92), "Belkin International, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(93), "Realtek Semiconductor Corporation");
    manufacturerIDStrings.put(Integer.valueOf(94), "Stonestreet One, LLC");
    manufacturerIDStrings.put(Integer.valueOf(95), "Wicentric, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(96), "RivieraWaves S.A.S");
    manufacturerIDStrings.put(Integer.valueOf(97), "RDA Microelectronics");
    manufacturerIDStrings.put(Integer.valueOf(98), "Gibson Guitars");
    manufacturerIDStrings.put(Integer.valueOf(99), "MiCommand Inc.");
    manufacturerIDStrings.put(Integer.valueOf(100), "Band XI International, LLC");
    manufacturerIDStrings.put(Integer.valueOf(101), "Hewlett-Packard Company");
    manufacturerIDStrings.put(Integer.valueOf(102), "9Solutions Oy");
    manufacturerIDStrings.put(Integer.valueOf(103), "GN Netcom A/S");
    manufacturerIDStrings.put(Integer.valueOf(104), "General Motors");
    manufacturerIDStrings.put(Integer.valueOf(105), "A&D Engineering, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(106), "MindTree Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(107), "Polar Electro OY");
    manufacturerIDStrings.put(Integer.valueOf(108), "Beautiful Enterprise Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(109), "BriarTek, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(110), "Summit Data Communications, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(111), "Sound ID");
    manufacturerIDStrings.put(Integer.valueOf(112), "Monster, LLC");
    manufacturerIDStrings.put(Integer.valueOf(113), "connectBlue AB");
    manufacturerIDStrings.put(Integer.valueOf(114), "ShangHai Super Smart Electronics Co. Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(115), "Group Sense Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(116), "Zomm, LLC");
    manufacturerIDStrings.put(Integer.valueOf(117), "Samsung Electronics Co. Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(118), "Creative Technology Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(119), "Laird Technologies");
    manufacturerIDStrings.put(Integer.valueOf(120), "Nike, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(121), "lesswire AG");
    manufacturerIDStrings.put(Integer.valueOf(122), "MStar Semiconductor, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(123), "Hanlynn Technologies");
    manufacturerIDStrings.put(Integer.valueOf(124), "A & R Cambridge");
    manufacturerIDStrings.put(Integer.valueOf(125), "Seers Technology Co. Ltd");
    manufacturerIDStrings.put(Integer.valueOf(126), "Sports Tracking Technologies Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(127), "Autonet Mobile");
    manufacturerIDStrings.put(Integer.valueOf(128), "DeLorme Publishing Company, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(129), "WuXi Vimicro");
    manufacturerIDStrings.put(Integer.valueOf(130), "Sennheiser Communications A/S");
    manufacturerIDStrings.put(Integer.valueOf(131), "TimeKeeping Systems, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(132), "Ludus Helsinki Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(133), "BlueRadios, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(134), "equinox AG");
    manufacturerIDStrings.put(Integer.valueOf(135), "Garmin International, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(136), "Ecotest");
    manufacturerIDStrings.put(Integer.valueOf(137), "GN ReSound A/S");
    manufacturerIDStrings.put(Integer.valueOf(138), "Jawbone");
    manufacturerIDStrings.put(Integer.valueOf(139), "Topcon Positioning Systems, LLC");
    manufacturerIDStrings.put(Integer.valueOf(140), "Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)");
    manufacturerIDStrings.put(Integer.valueOf(141), "Zscan Software");
    manufacturerIDStrings.put(Integer.valueOf(142), "Quintic Corp.");
    manufacturerIDStrings.put(Integer.valueOf(143), "Telit Wireless Solutions GmbH (Formerly Stollman E+V GmbH)");
    manufacturerIDStrings.put(Integer.valueOf(144), "Funai Electric Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(145), "Advanced PANMOBIL Systems GmbH & Co. KG");
    manufacturerIDStrings.put(Integer.valueOf(146), "ThinkOptics, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(147), "Universal Electronics, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(148), "Airoha Technology Corp.");
    manufacturerIDStrings.put(Integer.valueOf(149), "NEC Lighting, Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(150), "ODM Technology, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(151), "ConnecteDevice Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(152), "zer01.tv GmbH");
    manufacturerIDStrings.put(Integer.valueOf(153), "i.Tech Dynamic Global Distribution Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(154), "Alpwise");
    manufacturerIDStrings.put(Integer.valueOf(155), "Jiangsu Toppower Automotive Electronics Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(156), "Colorfy, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(157), "Geoforce Inc.");
    manufacturerIDStrings.put(Integer.valueOf(158), "Bose Corporation");
    manufacturerIDStrings.put(Integer.valueOf(159), "Suunto Oy");
    manufacturerIDStrings.put(Integer.valueOf(160), "Kensington Computer Products Group");
    manufacturerIDStrings.put(Integer.valueOf(161), "SR-Medizinelektronik");
    manufacturerIDStrings.put(Integer.valueOf(162), "Vertu Corporation Limited");
    manufacturerIDStrings.put(Integer.valueOf(163), "Meta Watch Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(164), "LINAK A/S");
    manufacturerIDStrings.put(Integer.valueOf(165), "OTL Dynamics LLC");
    manufacturerIDStrings.put(Integer.valueOf(166), "Panda Ocean Inc.");
    manufacturerIDStrings.put(Integer.valueOf(167), "Visteon Corporation");
    manufacturerIDStrings.put(Integer.valueOf(168), "ARP Devices Limited");
    manufacturerIDStrings.put(Integer.valueOf(169), "Magneti Marelli S.p.A");
    manufacturerIDStrings.put(Integer.valueOf(170), "CAEN RFID srl");
    manufacturerIDStrings.put(Integer.valueOf(171), "Ingenieur-Systemgruppe Zahn GmbH");
    manufacturerIDStrings.put(Integer.valueOf(172), "Green Throttle Games");
    manufacturerIDStrings.put(Integer.valueOf(173), "Peter Systemtechnik GmbH");
    manufacturerIDStrings.put(Integer.valueOf(174), "Omegawave Oy");
    manufacturerIDStrings.put(Integer.valueOf(175), "Cinetix");
    manufacturerIDStrings.put(Integer.valueOf(176), "Passif Semiconductor Corp");
    manufacturerIDStrings.put(Integer.valueOf(177), "Saris Cycling Group, Inc");
    manufacturerIDStrings.put(Integer.valueOf(178), "Bekey A/S");
    manufacturerIDStrings.put(Integer.valueOf(179), "Clarinox Technologies Pty. Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(180), "BDE Technology Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(181), "Swirl Networks");
    manufacturerIDStrings.put(Integer.valueOf(182), "Meso international");
    manufacturerIDStrings.put(Integer.valueOf(183), "TreLab Ltd");
    manufacturerIDStrings.put(Integer.valueOf(184), "Qualcomm Innovation Center, Inc. (QuIC)");
    manufacturerIDStrings.put(Integer.valueOf(185), "Johnson Controls, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(186), "Starkey Laboratories Inc.");
    manufacturerIDStrings.put(Integer.valueOf(187), "S-Power Electronics Limited");
    manufacturerIDStrings.put(Integer.valueOf(188), "Ace Sensor Inc");
    manufacturerIDStrings.put(Integer.valueOf(189), "Aplix Corporation");
    manufacturerIDStrings.put(Integer.valueOf(190), "AAMP of America");
    manufacturerIDStrings.put(Integer.valueOf(191), "Stalmart Technology Limited");
    manufacturerIDStrings.put(Integer.valueOf(192), "AMICCOM Electronics Corporation");
    manufacturerIDStrings.put(Integer.valueOf(193), "Shenzhen Excelsecu Data Technology Co.,Ltd");
    manufacturerIDStrings.put(Integer.valueOf(194), "Geneq Inc.");
    manufacturerIDStrings.put(Integer.valueOf(195), "adidas AG");
    manufacturerIDStrings.put(Integer.valueOf(196), "LG Electronics");
    manufacturerIDStrings.put(Integer.valueOf(197), "Onset Computer Corporation");
    manufacturerIDStrings.put(Integer.valueOf(198), "Selfly BV");
    manufacturerIDStrings.put(Integer.valueOf(199), "Quuppa Oy.");
    manufacturerIDStrings.put(Integer.valueOf(200), "GeLo Inc");
    manufacturerIDStrings.put(Integer.valueOf(201), "Evluma");
    manufacturerIDStrings.put(Integer.valueOf(202), "MC10");
    manufacturerIDStrings.put(Integer.valueOf(203), "Binauric SE");
    manufacturerIDStrings.put(Integer.valueOf(204), "Beats Electronics");
    manufacturerIDStrings.put(Integer.valueOf(205), "Microchip Technology Inc.");
    manufacturerIDStrings.put(Integer.valueOf(206), "Elgato Systems GmbH");
    manufacturerIDStrings.put(Integer.valueOf(207), "ARCHOS SA");
    manufacturerIDStrings.put(Integer.valueOf(208), "Dexcom, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(209), "Polar Electro Europe B.V.");
    manufacturerIDStrings.put(Integer.valueOf(210), "Dialog Semiconductor B.V.");
    manufacturerIDStrings.put(Integer.valueOf(211), "Taixingbang Technology (HK) Co,. LTD.");
    manufacturerIDStrings.put(Integer.valueOf(212), "Kawantech");
    manufacturerIDStrings.put(Integer.valueOf(213), "Austco Communication Systems");
    manufacturerIDStrings.put(Integer.valueOf(214), "Timex Group USA, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(215), "Qualcomm Technologies, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(216), "Qualcomm Connected Experiences, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(217), "Voyetra Turtle Beach");
    manufacturerIDStrings.put(Integer.valueOf(218), "txtr GmbH");
    manufacturerIDStrings.put(Integer.valueOf(219), "Biosentronics");
    manufacturerIDStrings.put(Integer.valueOf(220), "Procter & Gamble");
    manufacturerIDStrings.put(Integer.valueOf(221), "Hosiden Corporation");
    manufacturerIDStrings.put(Integer.valueOf(222), "Muzik LLC");
    manufacturerIDStrings.put(Integer.valueOf(223), "Misfit Wearables Corp");
    manufacturerIDStrings.put(Integer.valueOf(224), "Google");
    manufacturerIDStrings.put(Integer.valueOf(225), "Danlers Ltd");
    manufacturerIDStrings.put(Integer.valueOf(226), "Semilink Inc");
    manufacturerIDStrings.put(Integer.valueOf(227), "inMusic Brands, Inc");
    manufacturerIDStrings.put(Integer.valueOf(228), "L.S. Research Inc.");
    manufacturerIDStrings.put(Integer.valueOf(229), "Eden Software Consultants Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(230), "Freshtemp");
    manufacturerIDStrings.put(Integer.valueOf(231), "KS Technologies");
    manufacturerIDStrings.put(Integer.valueOf(232), "ACTS Technologies");
    manufacturerIDStrings.put(Integer.valueOf(233), "Vtrack Systems");
    manufacturerIDStrings.put(Integer.valueOf(234), "Nielsen-Kellerman Company");
    manufacturerIDStrings.put(Integer.valueOf(235), "Server Technology, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(236), "BioResearch Associates");
    manufacturerIDStrings.put(Integer.valueOf(237), "Jolly Logic, LLC");
    manufacturerIDStrings.put(Integer.valueOf(238), "Above Average Outcomes, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(239), "Bitsplitters GmbH");
    manufacturerIDStrings.put(Integer.valueOf(240), "PayPal, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(241), "Witron Technology Limited");
    manufacturerIDStrings.put(Integer.valueOf(242), "Aether Things Inc. (formerly Morse Project Inc.)");
    manufacturerIDStrings.put(Integer.valueOf(243), "Kent Displays Inc.");
    manufacturerIDStrings.put(Integer.valueOf(244), "Nautilus Inc.");
    manufacturerIDStrings.put(Integer.valueOf(245), "Smartifier Oy");
    manufacturerIDStrings.put(Integer.valueOf(246), "Elcometer Limited");
    manufacturerIDStrings.put(Integer.valueOf(247), "VSN Technologies Inc.");
    manufacturerIDStrings.put(Integer.valueOf(248), "AceUni Corp., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(249), "StickNFind");
    manufacturerIDStrings.put(Integer.valueOf(250), "Crystal Code AB");
    manufacturerIDStrings.put(Integer.valueOf(251), "KOUKAAM a.s.");
    manufacturerIDStrings.put(Integer.valueOf(252), "Delphi Corporation");
    manufacturerIDStrings.put(Integer.valueOf(253), "ValenceTech Limited");
    manufacturerIDStrings.put(Integer.valueOf(254), "Reserved");
    manufacturerIDStrings.put(Integer.valueOf(255), "Typo Products, LLC");
    manufacturerIDStrings.put(Integer.valueOf(256), "TomTom International BV");
    manufacturerIDStrings.put(Integer.valueOf(257), "Fugoo, Inc");
    manufacturerIDStrings.put(Integer.valueOf(258), "Keiser Corporation");
    manufacturerIDStrings.put(Integer.valueOf(259), "Bang & Olufsen A/S");
    manufacturerIDStrings.put(Integer.valueOf(260), "PLUS Locations Systems Pty Ltd");
    manufacturerIDStrings.put(Integer.valueOf(261), "Ubiquitous Computing Technology Corporation");
    manufacturerIDStrings.put(Integer.valueOf(262), "Innovative Yachtter Solutions");
    manufacturerIDStrings.put(Integer.valueOf(263), "William Demant Holding A/S");
    manufacturerIDStrings.put(Integer.valueOf(264), "Chicony Electronics Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(265), "Atus BV");
    manufacturerIDStrings.put(Integer.valueOf(266), "Codegate Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(267), "ERi, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(268), "Transducers Direct, LLC");
    manufacturerIDStrings.put(Integer.valueOf(269), "Fujitsu Ten Limited");
    manufacturerIDStrings.put(Integer.valueOf(270), "Audi AG");
    manufacturerIDStrings.put(Integer.valueOf(271), "HiSilicon Technologies Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(272), "Nippon Seiki Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(273), "Steelseries ApS");
    manufacturerIDStrings.put(Integer.valueOf(274), "Visybl Inc.");
    manufacturerIDStrings.put(Integer.valueOf(275), "Openbrain Technologies, Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(276), "Xensr");
    manufacturerIDStrings.put(Integer.valueOf(277), "e.solutions");
    manufacturerIDStrings.put(Integer.valueOf(278), "1OAK Technologies");
    manufacturerIDStrings.put(Integer.valueOf(279), "Wimoto Technologies Inc");
    manufacturerIDStrings.put(Integer.valueOf(280), "Radius Networks, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(281), "Wize Technology Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(282), "Qualcomm Labs, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(283), "Aruba Networks");
    manufacturerIDStrings.put(Integer.valueOf(284), "Baidu");
    manufacturerIDStrings.put(Integer.valueOf(285), "Arendi AG");
    manufacturerIDStrings.put(Integer.valueOf(286), "Skoda Auto a.s.");
    manufacturerIDStrings.put(Integer.valueOf(287), "Volkswagen AG");
    manufacturerIDStrings.put(Integer.valueOf(288), "Porsche AG");
    manufacturerIDStrings.put(Integer.valueOf(289), "Sino Wealth Electronic Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(290), "AirTurn, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(291), "Kinsa, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(292), "HID Global");
    manufacturerIDStrings.put(Integer.valueOf(293), "SEAT es");
    manufacturerIDStrings.put(Integer.valueOf(294), "Promethean Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(295), "Salutica Allied Solutions");
    manufacturerIDStrings.put(Integer.valueOf(296), "GPSI Group Pty Ltd");
    manufacturerIDStrings.put(Integer.valueOf(297), "Nimble Devices Oy");
    manufacturerIDStrings.put(Integer.valueOf(298), "Changzhou Yongse Infotech Co., Ltd");
    manufacturerIDStrings.put(Integer.valueOf(299), "SportIQ");
    manufacturerIDStrings.put(Integer.valueOf(300), "TEMEC Instruments B.V.");
    manufacturerIDStrings.put(Integer.valueOf(301), "Sony Corporation");
    manufacturerIDStrings.put(Integer.valueOf(302), "ASSA ABLOY");
    manufacturerIDStrings.put(Integer.valueOf(303), "Clarion Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(304), "Warehouse Innovations");
    manufacturerIDStrings.put(Integer.valueOf(305), "Cypress Semiconductor Corporation");
    manufacturerIDStrings.put(Integer.valueOf(306), "MADS Inc");
    manufacturerIDStrings.put(Integer.valueOf(307), "Blue Maestro Limited");
    manufacturerIDStrings.put(Integer.valueOf(308), "Resolution Products, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(309), "Airewear LLC");
    manufacturerIDStrings.put(Integer.valueOf(310), "Seed Labs, Inc. (formerly ETC sp. z.o.o.)");
    manufacturerIDStrings.put(Integer.valueOf(311), "Prestigio Plaza Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(312), "NTEO Inc.");
    manufacturerIDStrings.put(Integer.valueOf(313), "Focus Systems Corporation");
    manufacturerIDStrings.put(Integer.valueOf(314), "Tencent Holdings Limited");
    manufacturerIDStrings.put(Integer.valueOf(315), "Allegion");
    manufacturerIDStrings.put(Integer.valueOf(316), "Murata Manufacuring Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(318), "Nod, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(319), "B&B Manufacturing Company");
    manufacturerIDStrings.put(Integer.valueOf(320), "Alpine Electronics (China) Co., Ltd");
    manufacturerIDStrings.put(Integer.valueOf(321), "FedEx Services");
    manufacturerIDStrings.put(Integer.valueOf(322), "Grape Systems Inc.");
    manufacturerIDStrings.put(Integer.valueOf(323), "Bkon Connect");
    manufacturerIDStrings.put(Integer.valueOf(324), "Lintech GmbH");
    manufacturerIDStrings.put(Integer.valueOf(325), "Novatel Wireless");
    manufacturerIDStrings.put(Integer.valueOf(326), "Ciright");
    manufacturerIDStrings.put(Integer.valueOf(327), "Mighty Cast, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(328), "Ambimat Electronics");
    manufacturerIDStrings.put(Integer.valueOf(329), "Perytons Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(330), "Tivoli Audio, LLC");
    manufacturerIDStrings.put(Integer.valueOf(331), "Master Lock");
    manufacturerIDStrings.put(Integer.valueOf(332), "Mesh-Net Ltd");
    manufacturerIDStrings.put(Integer.valueOf(333), "Huizhou Desay SV Automotive CO., LTD.");
    manufacturerIDStrings.put(Integer.valueOf(334), "Tangerine, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(335), "B&W Group Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(336), "Pioneer Corporation");
    manufacturerIDStrings.put(Integer.valueOf(337), "OnBeep");
    manufacturerIDStrings.put(Integer.valueOf(338), "Vernier Software & Technology");
    manufacturerIDStrings.put(Integer.valueOf(339), "ROL Ergo");
    manufacturerIDStrings.put(Integer.valueOf(340), "Pebble Technology");
    manufacturerIDStrings.put(Integer.valueOf(341), "NETATMO");
    manufacturerIDStrings.put(Integer.valueOf(342), "Accumulate AB");
    manufacturerIDStrings.put(Integer.valueOf(343), "Anhui Huami Information Technology Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(344), "Inmite s.r.o.");
    manufacturerIDStrings.put(Integer.valueOf(345), "ChefSteps, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(346), "micas AG");
    manufacturerIDStrings.put(Integer.valueOf(347), "Biomedical Research Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(348), "Pitius Tec S.L.");
    manufacturerIDStrings.put(Integer.valueOf(349), "Estimote, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(350), "Unikey Technologies, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(351), "Timer Cap Co.");
    manufacturerIDStrings.put(Integer.valueOf(352), "AwoX");
    manufacturerIDStrings.put(Integer.valueOf(353), "yikes");
    manufacturerIDStrings.put(Integer.valueOf(354), "MADSGlobal NZ Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(355), "PCH International");
    manufacturerIDStrings.put(Integer.valueOf(356), "Qingdao Yeelink Information Technology Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(357), "Milwaukee Tool (formerly Milwaukee Electric Tools)");
    manufacturerIDStrings.put(Integer.valueOf(358), "MISHIK Pte Ltd");
    manufacturerIDStrings.put(Integer.valueOf(359), "Bayer HealthCare");
    manufacturerIDStrings.put(Integer.valueOf(360), "Spicebox LLC");
    manufacturerIDStrings.put(Integer.valueOf(361), "emberlight");
    manufacturerIDStrings.put(Integer.valueOf(362), "Cooper-Atkins Corporation");
    manufacturerIDStrings.put(Integer.valueOf(363), "Qblinks");
    manufacturerIDStrings.put(Integer.valueOf(364), "MYSPHERA");
    manufacturerIDStrings.put(Integer.valueOf(365), "LifeScan Inc");
    manufacturerIDStrings.put(Integer.valueOf(366), "Volantic AB");
    manufacturerIDStrings.put(Integer.valueOf(367), "Podo Labs, Inc");
    manufacturerIDStrings.put(Integer.valueOf(368), "F. Hoffmann-La Roche AG");
    manufacturerIDStrings.put(Integer.valueOf(369), "Amazon Fulfillment Service");
    manufacturerIDStrings.put(Integer.valueOf(370), "Connovate Technology Private Limited");
    manufacturerIDStrings.put(Integer.valueOf(371), "Kocomojo, LLC");
    manufacturerIDStrings.put(Integer.valueOf(372), "Everykey LLC");
    manufacturerIDStrings.put(Integer.valueOf(373), "Dynamic Controls");
    manufacturerIDStrings.put(Integer.valueOf(374), "SentriLock");
    manufacturerIDStrings.put(Integer.valueOf(375), "I-SYST inc.");
    manufacturerIDStrings.put(Integer.valueOf(376), "CASIO COMPUTER CO., LTD.");
    manufacturerIDStrings.put(Integer.valueOf(377), "LAPIS Semiconductor Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(378), "Telemonitor, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(379), "taskit GmbH");
    manufacturerIDStrings.put(Integer.valueOf(380), "Daimler AG");
    manufacturerIDStrings.put(Integer.valueOf(381), "BatAndCat");
    manufacturerIDStrings.put(Integer.valueOf(382), "BluDotz Ltd");
    manufacturerIDStrings.put(Integer.valueOf(383), "XTel ApS");
    manufacturerIDStrings.put(Integer.valueOf(384), "Gigaset Communications GmbH");
    manufacturerIDStrings.put(Integer.valueOf(385), "Gecko Health Innovations, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(386), "HOP Ubiquitous");
    manufacturerIDStrings.put(Integer.valueOf(387), "To Be Assigned");
    manufacturerIDStrings.put(Integer.valueOf(388), "Nectar");
    manufacturerIDStrings.put(Integer.valueOf(389), "bel'apps LLC");
    manufacturerIDStrings.put(Integer.valueOf(390), "CORE Lighting Ltd");
    manufacturerIDStrings.put(Integer.valueOf(391), "Seraphim Sense Ltd");
    manufacturerIDStrings.put(Integer.valueOf(392), "Unico RBC");
    manufacturerIDStrings.put(Integer.valueOf(393), "Physical Enterprises Inc.");
    manufacturerIDStrings.put(Integer.valueOf(394), "Able Trend Technology Limited");
    manufacturerIDStrings.put(Integer.valueOf(395), "Konica Minolta, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(396), "Wilo SE");
    manufacturerIDStrings.put(Integer.valueOf(397), "Extron Design Services");
    manufacturerIDStrings.put(Integer.valueOf(398), "Fitbit, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(399), "Fireflies Systems");
    manufacturerIDStrings.put(Integer.valueOf(400), "Intelletto Technologies Inc.");
    manufacturerIDStrings.put(Integer.valueOf(401), "FDK CORPORATION");
    manufacturerIDStrings.put(Integer.valueOf(402), "Cloudleaf, Inc");
    manufacturerIDStrings.put(Integer.valueOf(403), "Maveric Automation LLC");
    manufacturerIDStrings.put(Integer.valueOf(404), "Acoustic Stream Corporation");
    manufacturerIDStrings.put(Integer.valueOf(405), "Zuli");
    manufacturerIDStrings.put(Integer.valueOf(406), "Paxton Access Ltd");
    manufacturerIDStrings.put(Integer.valueOf(407), "WiSilica Inc");
    manufacturerIDStrings.put(Integer.valueOf(408), "VENGIT Korlátolt Felelősségű Társaság");
    manufacturerIDStrings.put(Integer.valueOf(409), "SALTO SYSTEMS S.L.");
    manufacturerIDStrings.put(Integer.valueOf(410), "TRON Forum (formerly T-Engine Forum)");
    manufacturerIDStrings.put(Integer.valueOf(411), "CUBETECH s.r.o.");
    manufacturerIDStrings.put(Integer.valueOf(412), "Cokiya Incorporated");
    manufacturerIDStrings.put(Integer.valueOf(413), "CVS Health");
    manufacturerIDStrings.put(Integer.valueOf(414), "Ceruus");
    manufacturerIDStrings.put(Integer.valueOf(415), "Strainstall Ltd");
    manufacturerIDStrings.put(Integer.valueOf(416), "Channel Enterprises (HK) Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(417), "FIAMM");
    manufacturerIDStrings.put(Integer.valueOf(418), "GIGALANE.CO.,LTD");
    manufacturerIDStrings.put(Integer.valueOf(419), "EROAD");
    manufacturerIDStrings.put(Integer.valueOf(420), "Mine Safety Appliances");
    manufacturerIDStrings.put(Integer.valueOf(421), "Icon Health and Fitness");
    manufacturerIDStrings.put(Integer.valueOf(422), "Asandoo GmbH");
    manufacturerIDStrings.put(Integer.valueOf(423), "ENERGOUS CORPORATION");
    manufacturerIDStrings.put(Integer.valueOf(424), "Taobao");
    manufacturerIDStrings.put(Integer.valueOf(425), "Canon Inc.");
    manufacturerIDStrings.put(Integer.valueOf(426), "Geophysical Technology Inc.");
    manufacturerIDStrings.put(Integer.valueOf(427), "Facebook, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(428), "Nipro Diagnostics, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(429), "FlightSafety International");
    manufacturerIDStrings.put(Integer.valueOf(430), "Earlens Corporation");
    manufacturerIDStrings.put(Integer.valueOf(431), "Sunrise Micro Devices, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(432), "Star Micronics Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(433), "Netizens Sp. z o.o.");
    manufacturerIDStrings.put(Integer.valueOf(434), "Nymi Inc.");
    manufacturerIDStrings.put(Integer.valueOf(435), "Nytec, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(436), "Trineo Sp. z o.o.");
    manufacturerIDStrings.put(Integer.valueOf(437), "Nest Labs Inc.");
    manufacturerIDStrings.put(Integer.valueOf(438), "LM Technologies Ltd");
    manufacturerIDStrings.put(Integer.valueOf(439), "General Electric Company");
    manufacturerIDStrings.put(Integer.valueOf(440), "i+D3 S.L.");
    manufacturerIDStrings.put(Integer.valueOf(441), "HANA Micron");
    manufacturerIDStrings.put(Integer.valueOf(442), "Stages Cycling LLC");
    manufacturerIDStrings.put(Integer.valueOf(443), "Cochlear Bone Anchored Solutions AB");
    manufacturerIDStrings.put(Integer.valueOf(444), "SenionLab AB");
    manufacturerIDStrings.put(Integer.valueOf(445), "Syszone Co., Ltd");
    manufacturerIDStrings.put(Integer.valueOf(446), "Pulsate Mobile Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(447), "Hong Kong HunterSun Electronic Limited");
    manufacturerIDStrings.put(Integer.valueOf(448), "pironex GmbH");
    manufacturerIDStrings.put(Integer.valueOf(449), "BRADATECH Corp.");
    manufacturerIDStrings.put(Integer.valueOf(450), "Transenergooil AG");
    manufacturerIDStrings.put(Integer.valueOf(451), "Bunch");
    manufacturerIDStrings.put(Integer.valueOf(452), "DME Microelectronics");
    manufacturerIDStrings.put(Integer.valueOf(453), "Bitcraze AB");
    manufacturerIDStrings.put(Integer.valueOf(454), "HASWARE Inc.");
    manufacturerIDStrings.put(Integer.valueOf(455), "Abiogenix Inc.");
    manufacturerIDStrings.put(Integer.valueOf(456), "Poly-Control ApS");
    manufacturerIDStrings.put(Integer.valueOf(457), "Avi-on");
    manufacturerIDStrings.put(Integer.valueOf(458), "Laerdal Medical AS");
    manufacturerIDStrings.put(Integer.valueOf(459), "Fetch My Pet");
    manufacturerIDStrings.put(Integer.valueOf(460), "Sam Labs Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(461), "Chengdu Synwing Technology Ltd");
    manufacturerIDStrings.put(Integer.valueOf(462), "HOUWA SYSTEM DESIGN, k.k.");
    manufacturerIDStrings.put(Integer.valueOf(463), "BSH");
    manufacturerIDStrings.put(Integer.valueOf(464), "Primus Inter Pares Ltd");
    manufacturerIDStrings.put(Integer.valueOf(465), "August");
    manufacturerIDStrings.put(Integer.valueOf(466), "Gill Electronics");
    manufacturerIDStrings.put(Integer.valueOf(467), "Sky Wave Design");
    manufacturerIDStrings.put(Integer.valueOf(468), "Newlab S.r.l.");
    manufacturerIDStrings.put(Integer.valueOf(469), "ELAD srl");
    manufacturerIDStrings.put(Integer.valueOf(470), "G-wearables inc.");
    manufacturerIDStrings.put(Integer.valueOf(471), "Squadrone Systems Inc.");
    manufacturerIDStrings.put(Integer.valueOf(472), "Code Corporation");
    manufacturerIDStrings.put(Integer.valueOf(473), "Savant Systems LLC");
    manufacturerIDStrings.put(Integer.valueOf(474), "Logitech International SA");
    manufacturerIDStrings.put(Integer.valueOf(475), "Innblue Consulting");
    manufacturerIDStrings.put(Integer.valueOf(476), "iParking Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(477), "Koninklijke Philips Electronics N.V.");
    manufacturerIDStrings.put(Integer.valueOf(478), "Minelab Electronics Pty Limited");
    manufacturerIDStrings.put(Integer.valueOf(479), "Bison Group Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(480), "Widex A/S");
    manufacturerIDStrings.put(Integer.valueOf(481), "Jolla Ltd");
    manufacturerIDStrings.put(Integer.valueOf(482), "Lectronix, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(483), "Caterpillar Inc");
    manufacturerIDStrings.put(Integer.valueOf(484), "Freedom Innovations");
    manufacturerIDStrings.put(Integer.valueOf(485), "Dynamic Devices Ltd");
    manufacturerIDStrings.put(Integer.valueOf(486), "Technology Solutions (UK) Ltd");
    manufacturerIDStrings.put(Integer.valueOf(487), "IPS Group Inc.");
    manufacturerIDStrings.put(Integer.valueOf(488), "STIR");
    manufacturerIDStrings.put(Integer.valueOf(489), "Sano, Inc");
    manufacturerIDStrings.put(Integer.valueOf(490), "Advanced Application Design, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(491), "AutoMap LLC");
    manufacturerIDStrings.put(Integer.valueOf(492), "Spreadtrum Communications Shanghai Ltd");
    manufacturerIDStrings.put(Integer.valueOf(493), "CuteCircuit LTD");
    manufacturerIDStrings.put(Integer.valueOf(494), "Valeo Service");
    manufacturerIDStrings.put(Integer.valueOf(495), "Fullpower Technologies, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(496), "KloudNation");
    manufacturerIDStrings.put(Integer.valueOf(497), "Zebra Technologies Corporation");
    manufacturerIDStrings.put(Integer.valueOf(498), "Itron, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(499), "The University of Tokyo");
    manufacturerIDStrings.put(Integer.valueOf(500), "UTC Fire and Security");
    manufacturerIDStrings.put(Integer.valueOf(501), "Cool Webthings Limited");
    manufacturerIDStrings.put(Integer.valueOf(502), "DJO Global");
    manufacturerIDStrings.put(Integer.valueOf(503), "Gelliner Limited");
    manufacturerIDStrings.put(Integer.valueOf(504), "Anyka (Guangzhou) Microelectronics Technology Co, LTD");
    manufacturerIDStrings.put(Integer.valueOf(505), "Medtronic, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(506), "Gozio, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(507), "Form Lifting, LLC");
    manufacturerIDStrings.put(Integer.valueOf(508), "Wahoo Fitness, LLC");
    manufacturerIDStrings.put(Integer.valueOf(509), "Kontakt Micro-Location Sp. z o.o.");
    manufacturerIDStrings.put(Integer.valueOf(510), "Radio System Corporation");
    manufacturerIDStrings.put(Integer.valueOf(511), "Freescale Semiconductor, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(512), "Verifone Systems PTe Ltd. Taiwan Branch");
    manufacturerIDStrings.put(Integer.valueOf(513), "AR Timing");
    manufacturerIDStrings.put(Integer.valueOf(514), "Rigado LLC");
    manufacturerIDStrings.put(Integer.valueOf(515), "Kemppi Oy");
    manufacturerIDStrings.put(Integer.valueOf(516), "Tapcentive Inc.");
    manufacturerIDStrings.put(Integer.valueOf(517), "Smartbotics Inc.");
    manufacturerIDStrings.put(Integer.valueOf(518), "Otter Products, LLC");
    manufacturerIDStrings.put(Integer.valueOf(519), "STEMP Inc.");
    manufacturerIDStrings.put(Integer.valueOf(520), "LumiGeek LLC");
    manufacturerIDStrings.put(Integer.valueOf(521), "InvisionHeart Inc.");
    manufacturerIDStrings.put(Integer.valueOf(522), "Macnica Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(523), "Jaguar Land Rover Limited");
    manufacturerIDStrings.put(Integer.valueOf(524), "CoroWare Technologies, Inc");
    manufacturerIDStrings.put(Integer.valueOf(525), "Simplo Technology Co., LTD");
    manufacturerIDStrings.put(Integer.valueOf(526), "Omron Healthcare Co., LTD");
    manufacturerIDStrings.put(Integer.valueOf(527), "Comodule GMBH");
    manufacturerIDStrings.put(Integer.valueOf(528), "ikeGPS");
    manufacturerIDStrings.put(Integer.valueOf(529), " Telink Semiconductor Co. Ltd");
    manufacturerIDStrings.put(Integer.valueOf(530), "Interplan Co., Ltd");
    manufacturerIDStrings.put(Integer.valueOf(531), "Wyler AG");
    manufacturerIDStrings.put(Integer.valueOf(532), "IK Multimedia Production srl");
    manufacturerIDStrings.put(Integer.valueOf(533), "Lukoton Experience Oy");
    manufacturerIDStrings.put(Integer.valueOf(534), "MTI Ltd");
    manufacturerIDStrings.put(Integer.valueOf(535), "Tech4home, Lda");
    manufacturerIDStrings.put(Integer.valueOf(536), "Hiotech AB");
    manufacturerIDStrings.put(Integer.valueOf(537), "DOTT Limited");
    manufacturerIDStrings.put(Integer.valueOf(538), "Blue Speck Labs, LLC");
    manufacturerIDStrings.put(Integer.valueOf(539), "Cisco Systems Inc");
    manufacturerIDStrings.put(Integer.valueOf(540), "Mobicomm Inc");
    manufacturerIDStrings.put(Integer.valueOf(541), "Edamic");
    manufacturerIDStrings.put(Integer.valueOf(542), "Goodnet Ltd");
    manufacturerIDStrings.put(Integer.valueOf(543), "Luster Leaf Products Inc");
    manufacturerIDStrings.put(Integer.valueOf(544), "Manus Machina BV");
    manufacturerIDStrings.put(Integer.valueOf(545), "Mobiquity Networks Inc");
    manufacturerIDStrings.put(Integer.valueOf(546), "Praxis Dynamics");
    manufacturerIDStrings.put(Integer.valueOf(547), "Philip Morris Products S.A.");
    manufacturerIDStrings.put(Integer.valueOf(548), "Comarch SA");
    manufacturerIDStrings.put(Integer.valueOf(549), "Nestlé Nespresso S.A.");
    manufacturerIDStrings.put(Integer.valueOf(550), "Merlinia A/S");
    manufacturerIDStrings.put(Integer.valueOf(551), "LifeBEAM Technologies");
    manufacturerIDStrings.put(Integer.valueOf(552), "Twocanoes Labs, LLC");
    manufacturerIDStrings.put(Integer.valueOf(553), "Muoverti Limited");
    manufacturerIDStrings.put(Integer.valueOf(554), "Stamer Musikanlagen GMBH");
    manufacturerIDStrings.put(Integer.valueOf(555), "Tesla Motors");
    manufacturerIDStrings.put(Integer.valueOf(556), "Pharynks Corporation");
    manufacturerIDStrings.put(Integer.valueOf(557), "Lupine");
    manufacturerIDStrings.put(Integer.valueOf(558), "Siemens AG");
    manufacturerIDStrings.put(Integer.valueOf(559), "Huami (Shanghai) Culture Communication CO., LTD");
    manufacturerIDStrings.put(Integer.valueOf(560), "Foster Electric Company, Ltd");
    manufacturerIDStrings.put(Integer.valueOf(561), "ETA SA");
    manufacturerIDStrings.put(Integer.valueOf(562), " x-Senso Solutions Kft");
    manufacturerIDStrings.put(Integer.valueOf(563), " Shenzhen SuLong Communication Ltd");
    manufacturerIDStrings.put(Integer.valueOf(564), " FengFan (BeiJing) Technology Co, Ltd");
    manufacturerIDStrings.put(Integer.valueOf(565), " Qrio Inc");
    manufacturerIDStrings.put(Integer.valueOf(566), " Pitpatpet Ltd");
    manufacturerIDStrings.put(Integer.valueOf(567), " MSHeli s.r.l.");
    manufacturerIDStrings.put(Integer.valueOf(568), "Trakm8 Ltd");
    manufacturerIDStrings.put(Integer.valueOf(569), "JIN CO, Ltd");
    manufacturerIDStrings.put(Integer.valueOf(570), "Alatech Technology");
    manufacturerIDStrings.put(Integer.valueOf(571), "Beijing CarePulse Electronic Technology Co, Ltd");
    manufacturerIDStrings.put(Integer.valueOf(572), "Awarepoint");
    manufacturerIDStrings.put(Integer.valueOf(573), "ViCentra B.V.");
    manufacturerIDStrings.put(Integer.valueOf(574), "Raven Industries");
    manufacturerIDStrings.put(Integer.valueOf(575), "WaveWare Technologies");
    manufacturerIDStrings.put(Integer.valueOf(576), "Argenox Technologies");
    manufacturerIDStrings.put(Integer.valueOf(577), "Bragi GmbH");
    manufacturerIDStrings.put(Integer.valueOf(578), "16Lab Inc");
    manufacturerIDStrings.put(Integer.valueOf(579), "Masimo Corp");
    manufacturerIDStrings.put(Integer.valueOf(580), "Iotera Inc.");
    manufacturerIDStrings.put(Integer.valueOf(581), "Endress+Hauser");
    manufacturerIDStrings.put(Integer.valueOf(582), "ACKme Networks, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(583), "FiftyThree Inc.");
    manufacturerIDStrings.put(Integer.valueOf(584), "Parker Hannifin Corp");
    manufacturerIDStrings.put(Integer.valueOf(585), "Transcranial Ltd");
    manufacturerIDStrings.put(Integer.valueOf(586), "Uwatec AG");
    manufacturerIDStrings.put(Integer.valueOf(587), "Orlan LLC");
    manufacturerIDStrings.put(Integer.valueOf(588), "Blue Clover Devices");
    manufacturerIDStrings.put(Integer.valueOf(589), "M-Way Solutions GmbH");
    manufacturerIDStrings.put(Integer.valueOf(590), "Microtronics Engineering GmbH");
    manufacturerIDStrings.put(Integer.valueOf(591), "Schneider Schreibgeräte GmbH");
    manufacturerIDStrings.put(Integer.valueOf(592), "Sapphire Circuits LLC");
    manufacturerIDStrings.put(Integer.valueOf(593), "Lumo Bodytech Inc.");
    manufacturerIDStrings.put(Integer.valueOf(594), "UKC Technosolution");
    manufacturerIDStrings.put(Integer.valueOf(595), "Xicato Inc.");
    manufacturerIDStrings.put(Integer.valueOf(596), "Playbrush");
    manufacturerIDStrings.put(Integer.valueOf(597), "Dai Nippon Printing Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(598), "G24 Power Limited");
    manufacturerIDStrings.put(Integer.valueOf(599), "AdBabble Local Commerce Inc.");
    manufacturerIDStrings.put(Integer.valueOf(600), "Devialet SA");
    manufacturerIDStrings.put(Integer.valueOf(601), "ALTYOR");
    manufacturerIDStrings.put(Integer.valueOf(602), "University of Applied Sciences Valais/Haute Ecole Valaisanne");
    manufacturerIDStrings.put(Integer.valueOf(603), "Five Interactive, LLC dba Zendo");
    manufacturerIDStrings.put(Integer.valueOf(604), "NetEase (Hangzhou) Network co.Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(605), "Lexmark International Inc.");
    manufacturerIDStrings.put(Integer.valueOf(606), "Fluke Corporation");
    manufacturerIDStrings.put(Integer.valueOf(607), "Yardarm Technologies");
    manufacturerIDStrings.put(Integer.valueOf(608), "SensaRx");
    manufacturerIDStrings.put(Integer.valueOf(609), "SECVRE GmbH");
    manufacturerIDStrings.put(Integer.valueOf(610), "Glacial Ridge Technologies");
    manufacturerIDStrings.put(Integer.valueOf(611), "Identiv, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(612), "DDS, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(613), "SMK Corporation");
    manufacturerIDStrings.put(Integer.valueOf(614), "Schawbel Technologies LLC");
    manufacturerIDStrings.put(Integer.valueOf(615), "XMI Systems SA");
    manufacturerIDStrings.put(Integer.valueOf(616), "Cerevo");
    manufacturerIDStrings.put(Integer.valueOf(617), "Torrox GmbH & Co KG");
    manufacturerIDStrings.put(Integer.valueOf(618), "Gemalto");
    manufacturerIDStrings.put(Integer.valueOf(619), "DEKA Research & Development Corp.");
    manufacturerIDStrings.put(Integer.valueOf(620), "Domster Tadeusz Szydlowski");
    manufacturerIDStrings.put(Integer.valueOf(621), "Technogym SPA");
    manufacturerIDStrings.put(Integer.valueOf(622), "FLEURBAEY BVBA");
    manufacturerIDStrings.put(Integer.valueOf(623), "Aptcode Solutions");
    manufacturerIDStrings.put(Integer.valueOf(624), "LSI ADL Technology");
    manufacturerIDStrings.put(Integer.valueOf(625), "Animas Corp");
    manufacturerIDStrings.put(Integer.valueOf(626), "Alps Electric Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(627), "OCEASOFT");
    manufacturerIDStrings.put(Integer.valueOf(628), "Motsai Research");
    manufacturerIDStrings.put(Integer.valueOf(629), "Geotab");
    manufacturerIDStrings.put(Integer.valueOf(630), "E.G.O. Elektro-Gerätebau GmbH");
    manufacturerIDStrings.put(Integer.valueOf(631), "bewhere inc");
    manufacturerIDStrings.put(Integer.valueOf(632), "Johnson Outdoors Inc");
    manufacturerIDStrings.put(Integer.valueOf(633), "steute Schaltgerate GmbH & Co. KG");
    manufacturerIDStrings.put(Integer.valueOf(634), "Ekomini inc.");
    manufacturerIDStrings.put(Integer.valueOf(635), "DEFA AS");
    manufacturerIDStrings.put(Integer.valueOf(636), "Aseptika Ltd");
    manufacturerIDStrings.put(Integer.valueOf(637), "HUAWEI Technologies Co., Ltd. ( 华为技术有限公司 )");
    manufacturerIDStrings.put(Integer.valueOf(638), "HabitAware, LLC");
    manufacturerIDStrings.put(Integer.valueOf(639), "ruwido austria gmbh");
    manufacturerIDStrings.put(Integer.valueOf(640), "ITEC corporation");
    manufacturerIDStrings.put(Integer.valueOf(641), "StoneL");
    manufacturerIDStrings.put(Integer.valueOf(642), "Sonova AG");
    manufacturerIDStrings.put(Integer.valueOf(643), "Maven Machines, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(644), "Synapse Electronics");
    manufacturerIDStrings.put(Integer.valueOf(645), "Standard Innovation Inc.");
    manufacturerIDStrings.put(Integer.valueOf(646), "RF Code, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(647), "Wally Ventures S.L.");
    manufacturerIDStrings.put(Integer.valueOf(648), "Willowbank Electronics Ltd");
    manufacturerIDStrings.put(Integer.valueOf(649), "SK Telecom");
    manufacturerIDStrings.put(Integer.valueOf(650), "Jetro AS");
    manufacturerIDStrings.put(Integer.valueOf(651), "Code Gears LTD");
    manufacturerIDStrings.put(Integer.valueOf(652), "NANOLINK APS");
    manufacturerIDStrings.put(Integer.valueOf(653), "IF, LLC");
    manufacturerIDStrings.put(Integer.valueOf(654), "RF Digital Corp");
    manufacturerIDStrings.put(Integer.valueOf(655), "Church & Dwight Co., Inc");
    manufacturerIDStrings.put(Integer.valueOf(656), "Multibit Oy");
    manufacturerIDStrings.put(Integer.valueOf(657), "CliniCloud Inc");
    manufacturerIDStrings.put(Integer.valueOf(658), "SwiftSensors");
    manufacturerIDStrings.put(Integer.valueOf(659), "Blue Bite");
    manufacturerIDStrings.put(Integer.valueOf(660), "ELIAS GmbH");
    manufacturerIDStrings.put(Integer.valueOf(661), "Sivantos GmbH");
    manufacturerIDStrings.put(Integer.valueOf(662), "Petzl");
    manufacturerIDStrings.put(Integer.valueOf(663), "storm power ltd");
    manufacturerIDStrings.put(Integer.valueOf(664), "EISST Ltd");
    manufacturerIDStrings.put(Integer.valueOf(665), "Inexess Technology Simma KG");
    manufacturerIDStrings.put(Integer.valueOf(666), "Currant, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(667), "C2 Development, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(668), "Blue Sky Scientific, LLC");
    manufacturerIDStrings.put(Integer.valueOf(669), "ALOTTAZS LABS, LLC");
    manufacturerIDStrings.put(Integer.valueOf(670), "Kupson spol. s r.o.");
    manufacturerIDStrings.put(Integer.valueOf(671), "Areus Engineering GmbH");
    manufacturerIDStrings.put(Integer.valueOf(672), "Impossible Camera GmbH");
    manufacturerIDStrings.put(Integer.valueOf(673), "InventureTrack Systems");
    manufacturerIDStrings.put(Integer.valueOf(674), "LockedUp");
    manufacturerIDStrings.put(Integer.valueOf(675), "Itude");
    manufacturerIDStrings.put(Integer.valueOf(676), "Pacific Lock Company");
    manufacturerIDStrings.put(Integer.valueOf(677), "Tendyron Corporation ( 天地融科技股份有限公司 )");
    manufacturerIDStrings.put(Integer.valueOf(678), "Robert Bosch GmbH");
    manufacturerIDStrings.put(Integer.valueOf(679), "Illuxtron international B.V.");
    manufacturerIDStrings.put(Integer.valueOf(680), "miSport Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(681), "Chargelib");
    manufacturerIDStrings.put(Integer.valueOf(682), "Doppler Lab");
    manufacturerIDStrings.put(Integer.valueOf(683), "BBPOS Limited");
    manufacturerIDStrings.put(Integer.valueOf(684), "RTB Elektronik GmbH & Co. KG");
    manufacturerIDStrings.put(Integer.valueOf(685), "Rx Networks, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(686), "WeatherFlow, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(687), "Technicolor USA Inc.");
    manufacturerIDStrings.put(Integer.valueOf(688), "Bestechnic(Shanghai),Ltd");
    manufacturerIDStrings.put(Integer.valueOf(689), "Raden Inc");
    manufacturerIDStrings.put(Integer.valueOf(690), "JouZen Oy");
    manufacturerIDStrings.put(Integer.valueOf(691), "CLABER S.P.A.");
    manufacturerIDStrings.put(Integer.valueOf(692), "Hyginex, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(693), "HANSHIN ELECTRIC RAILWAY CO.,LTD.");
    manufacturerIDStrings.put(Integer.valueOf(694), "Schneider Electric");
    manufacturerIDStrings.put(Integer.valueOf(695), "Oort Technologies LLC");
    manufacturerIDStrings.put(Integer.valueOf(696), "Chrono Therapeutics");
    manufacturerIDStrings.put(Integer.valueOf(697), "Rinnai Corporation");
    manufacturerIDStrings.put(Integer.valueOf(698), "Swissprime Technologies AG");
    manufacturerIDStrings.put(Integer.valueOf(699), "Koha.,Co.Ltd");
    manufacturerIDStrings.put(Integer.valueOf(700), "Genevac Ltd");
    manufacturerIDStrings.put(Integer.valueOf(701), "Chemtronics");
    manufacturerIDStrings.put(Integer.valueOf(702), "Seguro Technology Sp. z o.o.");
    manufacturerIDStrings.put(Integer.valueOf(703), "Redbird Flight Simulations");
    manufacturerIDStrings.put(Integer.valueOf(704), "Dash Robotics");
    manufacturerIDStrings.put(Integer.valueOf(705), "LINE Corporation");
    manufacturerIDStrings.put(Integer.valueOf(706), "Guillemot Corporation");
    manufacturerIDStrings.put(Integer.valueOf(707), "Techtronic Power Tools Technology Limited");
    manufacturerIDStrings.put(Integer.valueOf(708), "Wilson Sporting Goods");
    manufacturerIDStrings.put(Integer.valueOf(709), "Lenovo (Singapore) Pte Ltd. ( 联想（新加坡） )");
    manufacturerIDStrings.put(Integer.valueOf(710), "Ayatan Sensors");
    manufacturerIDStrings.put(Integer.valueOf(711), "Electronics Tomorrow Limited");
    manufacturerIDStrings.put(Integer.valueOf(712), "VASCO Data Security International, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(713), "PayRange Inc.");
    manufacturerIDStrings.put(Integer.valueOf(714), "ABOV Semiconductor");
    manufacturerIDStrings.put(Integer.valueOf(715), "AINA-Wireless Inc.");
    manufacturerIDStrings.put(Integer.valueOf(716), "Eijkelkamp Soil & Water");
    manufacturerIDStrings.put(Integer.valueOf(717), "BMA ergonomics b.v.");
    manufacturerIDStrings.put(Integer.valueOf(718), "Teva Branded Pharmaceutical Products R&D, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(719), "Anima");
    manufacturerIDStrings.put(Integer.valueOf(720), "3M");
    manufacturerIDStrings.put(Integer.valueOf(721), "Empatica Srl");
    manufacturerIDStrings.put(Integer.valueOf(722), "Afero, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(723), "Powercast Corporation");
    manufacturerIDStrings.put(Integer.valueOf(724), "Secuyou ApS");
    manufacturerIDStrings.put(Integer.valueOf(725), "OMRON Corporation");
    manufacturerIDStrings.put(Integer.valueOf(726), "Send Solutions");
    manufacturerIDStrings.put(Integer.valueOf(727), "NIPPON SYSTEMWARE CO.,LTD.");
    manufacturerIDStrings.put(Integer.valueOf(728), "Neosfar");
    manufacturerIDStrings.put(Integer.valueOf(729), "Fliegl Agrartechnik GmbH");
    manufacturerIDStrings.put(Integer.valueOf(730), "Gilvader");
    manufacturerIDStrings.put(Integer.valueOf(731), "Digi International Inc (R)");
    manufacturerIDStrings.put(Integer.valueOf(732), "DeWalch Technologies, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(733), "Flint Rehabilitation Devices, LLC");
    manufacturerIDStrings.put(Integer.valueOf(734), "Samsung SDS Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(735), "Blur Product Development");
    manufacturerIDStrings.put(Integer.valueOf(736), "University of Michigan");
    manufacturerIDStrings.put(Integer.valueOf(737), "Victron Energy BV");
    manufacturerIDStrings.put(Integer.valueOf(738), "NTT docomo");
    manufacturerIDStrings.put(Integer.valueOf(739), "Carmanah Technologies Corp.");
    manufacturerIDStrings.put(Integer.valueOf(740), "Bytestorm Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(741), "Espressif Incorporated ( 乐鑫信息科技(上海)有限公司 )");
    manufacturerIDStrings.put(Integer.valueOf(742), "Unwire");
    manufacturerIDStrings.put(Integer.valueOf(743), "Connected Yard, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(744), "American Music Environments");
    manufacturerIDStrings.put(Integer.valueOf(745), "Sensogram Technologies, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(746), "Fujitsu Limited");
    manufacturerIDStrings.put(Integer.valueOf(747), "Ardic Technology");
    manufacturerIDStrings.put(Integer.valueOf(748), "Delta Systems, Inc");
    manufacturerIDStrings.put(Integer.valueOf(749), "HTC Corporation");
    manufacturerIDStrings.put(Integer.valueOf(750), "Citizen Holdings Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(751), "SMART-INNOVATION.inc");
    manufacturerIDStrings.put(Integer.valueOf(752), "Blackrat Software");
    manufacturerIDStrings.put(Integer.valueOf(753), "The Idea Cave, LLC");
    manufacturerIDStrings.put(Integer.valueOf(754), "GoPro, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(755), "AuthAir, Inc");
    manufacturerIDStrings.put(Integer.valueOf(756), "Vensi, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(757), "Indagem Tech LLC");
    manufacturerIDStrings.put(Integer.valueOf(758), "Intemo Technologies");
    manufacturerIDStrings.put(Integer.valueOf(759), "DreamVisions co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(760), "Runteq Oy Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(761), "IMAGINATION TECHNOLOGIES LTD ");
    manufacturerIDStrings.put(Integer.valueOf(762), "CoSTAR Technologies ");
    manufacturerIDStrings.put(Integer.valueOf(763), "Clarius Mobile Health Corp. ");
    manufacturerIDStrings.put(Integer.valueOf(764), "Shanghai Frequen Microelectronics Co., Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(765), "Uwanna, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(766), "Lierda Science & Technology Group Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(767), "Silicon Laboratories");
    manufacturerIDStrings.put(Integer.valueOf(768), "World Moto Inc.");
    manufacturerIDStrings.put(Integer.valueOf(769), "Giatec Scientific Inc.");
    manufacturerIDStrings.put(Integer.valueOf(770), "Loop Devices, Inc");
    manufacturerIDStrings.put(Integer.valueOf(771), "IACA electronique ");
    manufacturerIDStrings.put(Integer.valueOf(772), "Martians Inc ");
    manufacturerIDStrings.put(Integer.valueOf(773), "Swipp ApS ");
    manufacturerIDStrings.put(Integer.valueOf(774), "Life Laboratory Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(775), "FUJI INDUSTRIAL CO.,LTD.");
    manufacturerIDStrings.put(Integer.valueOf(776), "Surefire, LLC ");
    manufacturerIDStrings.put(Integer.valueOf(777), "Dolby Labs ");
    manufacturerIDStrings.put(Integer.valueOf(778), "Ellisys ");
    manufacturerIDStrings.put(Integer.valueOf(779), "Magnitude Lighting Converters ");
    manufacturerIDStrings.put(Integer.valueOf(780), "Hilti AG ");
    manufacturerIDStrings.put(Integer.valueOf(781), "Devdata S.r.l. ");
    manufacturerIDStrings.put(Integer.valueOf(782), "Deviceworx ");
    manufacturerIDStrings.put(Integer.valueOf(783), "Shortcut Labs ");
    manufacturerIDStrings.put(Integer.valueOf(784), "SGL Italia S.r.l.");
    manufacturerIDStrings.put(Integer.valueOf(785), "");
    manufacturerIDStrings.put(Integer.valueOf(786), "");
    manufacturerIDStrings.put(Integer.valueOf(787), "");
    manufacturerIDStrings.put(Integer.valueOf(788), "");
    manufacturerIDStrings.put(Integer.valueOf(789), "");
    manufacturerIDStrings.put(Integer.valueOf(790), "AG Measurematics Pvt. Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(791), "CHUO Electronics CO., LTD. ");
    manufacturerIDStrings.put(Integer.valueOf(792), "Aspenta International ");
    manufacturerIDStrings.put(Integer.valueOf(793), "Eugster Frismag AG ");
    manufacturerIDStrings.put(Integer.valueOf(794), "Amber wireless GmbH");
    manufacturerIDStrings.put(Integer.valueOf(795), "HQ Inc");
    manufacturerIDStrings.put(Integer.valueOf(796), "Lab Sensor Solutions");
    manufacturerIDStrings.put(Integer.valueOf(797), "Enterlab ApS");
    manufacturerIDStrings.put(Integer.valueOf(798), "Eyefi, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(799), "MetaSystem S.p.A");
    manufacturerIDStrings.put(Integer.valueOf(800), "SONO ELECTRONICS. CO., LTD");
    manufacturerIDStrings.put(Integer.valueOf(801), "Jewelbots");
    manufacturerIDStrings.put(Integer.valueOf(802), "Compumedics Limited ");
    manufacturerIDStrings.put(Integer.valueOf(803), "Rotor Bike Components ");
    manufacturerIDStrings.put(Integer.valueOf(804), "Astro, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(805), "Amotus Solutions ");
    manufacturerIDStrings.put(Integer.valueOf(806), "Healthwear Technologies (Changzhou)Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(807), "Essex Electronics ");
    manufacturerIDStrings.put(Integer.valueOf(808), "Grundfos A/S ");
    manufacturerIDStrings.put(Integer.valueOf(809), "Eargo, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(810), "Electronic Design Lab ");
    manufacturerIDStrings.put(Integer.valueOf(811), "ESYLUX ");
    manufacturerIDStrings.put(Integer.valueOf(812), "NIPPON SMT.CO.,Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(813), "BM innovations GmbH");
    manufacturerIDStrings.put(Integer.valueOf(814), "indoormap ");
    manufacturerIDStrings.put(Integer.valueOf(815), "OttoQ Inc ");
    manufacturerIDStrings.put(Integer.valueOf(816), "North Pole Engineering ");
    manufacturerIDStrings.put(Integer.valueOf(817), "3flares Technologies Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(818), "Electrocompaniet A.S. ");
    manufacturerIDStrings.put(Integer.valueOf(819), "Mul-T-Lock ");
    manufacturerIDStrings.put(Integer.valueOf(820), "Corentium AS ");
    manufacturerIDStrings.put(Integer.valueOf(821), "Enlighted Inc ");
    manufacturerIDStrings.put(Integer.valueOf(822), "GISTIC ");
    manufacturerIDStrings.put(Integer.valueOf(823), "AJP2 Holdings, LLC ");
    manufacturerIDStrings.put(Integer.valueOf(824), "COBI GmbH ");
    manufacturerIDStrings.put(Integer.valueOf(825), "Blue Sky Scientific, LLC ");
    manufacturerIDStrings.put(Integer.valueOf(826), "Appception, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(827), "Courtney Thorne Limited ");
    manufacturerIDStrings.put(Integer.valueOf(828), "Virtuosys ");
    manufacturerIDStrings.put(Integer.valueOf(829), "TPV Technology Limited ");
    manufacturerIDStrings.put(Integer.valueOf(830), "Monitra SA ");
    manufacturerIDStrings.put(Integer.valueOf(831), "Automation Components, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(832), "Letsense s.r.l. ");
    manufacturerIDStrings.put(Integer.valueOf(833), "Etesian Technologies LLC ");
    manufacturerIDStrings.put(Integer.valueOf(834), "GERTEC BRASIL LTDA.");
    manufacturerIDStrings.put(Integer.valueOf(835), "Drekker Development Pty. Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(836), "Whirl Inc ");
    manufacturerIDStrings.put(Integer.valueOf(837), "Locus Positioning ");
    manufacturerIDStrings.put(Integer.valueOf(838), "Acuity Brands Lighting, Inc ");
    manufacturerIDStrings.put(Integer.valueOf(839), "Prevent Biometrics ");
    manufacturerIDStrings.put(Integer.valueOf(840), "Arioneo ");
    manufacturerIDStrings.put(Integer.valueOf(841), "VersaMe ");
    manufacturerIDStrings.put(Integer.valueOf(842), "Vaddio ");
    manufacturerIDStrings.put(Integer.valueOf(843), "Libratone A/S ");
    manufacturerIDStrings.put(Integer.valueOf(844), "HM Electronics, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(845), "TASER International, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(846), "Safe Trust Inc.");
    manufacturerIDStrings.put(Integer.valueOf(847), "Heartland Payment Systems ");
    manufacturerIDStrings.put(Integer.valueOf(848), "Bitstrata Systems Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(849), "Pieps GmbH ");
    manufacturerIDStrings.put(Integer.valueOf(850), "iRiding(Xiamen)Technology Co.,Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(851), "Alpha Audiotronics, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(852), "TOPPAN FORMS CO.,LTD. ");
    manufacturerIDStrings.put(Integer.valueOf(853), "Sigma Designs, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(854), "Spectrum Brands, Inc.");
    manufacturerIDStrings.put(Integer.valueOf(855), "Polymap Wireless ");
    manufacturerIDStrings.put(Integer.valueOf(856), "MagniWare Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(857), "Novotec Medical GmbH ");
    manufacturerIDStrings.put(Integer.valueOf(858), "Medicom Innovation Partner a/s ");
    manufacturerIDStrings.put(Integer.valueOf(859), "Matrix Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(860), "Eaton Corporation ");
    manufacturerIDStrings.put(Integer.valueOf(861), "KYS ");
    manufacturerIDStrings.put(Integer.valueOf(862), "Naya Health, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(863), "Acromag ");
    manufacturerIDStrings.put(Integer.valueOf(864), "Insulet Corporation ");
    manufacturerIDStrings.put(Integer.valueOf(865), "Wellinks Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(866), "ON Semiconductor ");
    manufacturerIDStrings.put(Integer.valueOf(867), "FREELAP SA ");
    manufacturerIDStrings.put(Integer.valueOf(868), "Favero Electronics Srl ");
    manufacturerIDStrings.put(Integer.valueOf(869), "BioMech Sensor LLC ");
    manufacturerIDStrings.put(Integer.valueOf(870), "BOLTT Sports technologies Private limited ");
    manufacturerIDStrings.put(Integer.valueOf(871), "Saphe International");
    manufacturerIDStrings.put(Integer.valueOf(872), "Metormote AB ");
    manufacturerIDStrings.put(Integer.valueOf(873), "littleBits ");
    manufacturerIDStrings.put(Integer.valueOf(874), "SetPoint Medical ");
    manufacturerIDStrings.put(Integer.valueOf(875), "BRControls Products BV ");
    manufacturerIDStrings.put(Integer.valueOf(876), "Zipcar ");
    manufacturerIDStrings.put(Integer.valueOf(877), "AirBolt Pty Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(878), "KeepTruckin Inc ");
    manufacturerIDStrings.put(Integer.valueOf(879), "Motiv, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(880), "Wazombi Labs OÜ ");
    manufacturerIDStrings.put(Integer.valueOf(881), "ORBCOMM ");
    manufacturerIDStrings.put(Integer.valueOf(882), "Nixie Labs, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(883), "AppNearMe Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(884), "Holman Industries ");
    manufacturerIDStrings.put(Integer.valueOf(885), "Expain AS");
    manufacturerIDStrings.put(Integer.valueOf(886), "Electronic Temperature Instruments Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(887), "Plejd AB ");
    manufacturerIDStrings.put(Integer.valueOf(888), "Propeller Health ");
    manufacturerIDStrings.put(Integer.valueOf(889), "Shenzhen iMCO Electronic Technology Co.,Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(890), "Algoria ");
    manufacturerIDStrings.put(Integer.valueOf(891), "Apption Labs Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(892), "Cronologics Corporation ");
    manufacturerIDStrings.put(Integer.valueOf(893), "MICRODIA Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(894), "lulabytes S.L. ");
    manufacturerIDStrings.put(Integer.valueOf(895), "Nestec S.A. ");
    manufacturerIDStrings.put(Integer.valueOf(896), "LLC MEGA-F service ");
    manufacturerIDStrings.put(Integer.valueOf(897), "Sharp Corporation ");
    manufacturerIDStrings.put(Integer.valueOf(898), "Precision Outcomes Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(899), "Kronos Incorporated ");
    manufacturerIDStrings.put(Integer.valueOf(900), "OCOSMOS Co., Ltd.");
    manufacturerIDStrings.put(Integer.valueOf(901), "Embedded Electronic Solutions Ltd. dba e2Solutions ");
    manufacturerIDStrings.put(Integer.valueOf(902), "Aterica Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(903), "BluStor PMC, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(904), "Kapsch TrafficCom AB");
    manufacturerIDStrings.put(Integer.valueOf(905), "ActiveBlu Corporation");
    manufacturerIDStrings.put(Integer.valueOf(906), "Kohler Mira Limited");
    manufacturerIDStrings.put(Integer.valueOf(907), "Noke");
    manufacturerIDStrings.put(Integer.valueOf(908), "Appion Inc.");
    manufacturerIDStrings.put(Integer.valueOf(909), "Resmed Ltd");
    manufacturerIDStrings.put(Integer.valueOf(910), "Crownstone B.V.");
    manufacturerIDStrings.put(Integer.valueOf(911), "Xiaomi Inc.");
    manufacturerIDStrings.put(Integer.valueOf(912), "INFOTECH s.r.o.");
    manufacturerIDStrings.put(Integer.valueOf(913), "Thingsquare AB ");
    manufacturerIDStrings.put(Integer.valueOf(914), "T&D ");
    manufacturerIDStrings.put(Integer.valueOf(915), "LAVAZZA S.p.A. ");
    manufacturerIDStrings.put(Integer.valueOf(916), "Netclearance Systems, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(917), "SDATAWAY ");
    manufacturerIDStrings.put(Integer.valueOf(918), "BLOKS GmbH ");
    manufacturerIDStrings.put(Integer.valueOf(919), "LEGO System A/S ");
    manufacturerIDStrings.put(Integer.valueOf(920), "Thetatronics Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(921), "Nikon Corporation ");
    manufacturerIDStrings.put(Integer.valueOf(922), "NeST ");
    manufacturerIDStrings.put(Integer.valueOf(923), "South Silicon Valley Microelectronics ");
    manufacturerIDStrings.put(Integer.valueOf(924), "ALE International ");
    manufacturerIDStrings.put(Integer.valueOf(925), "CareView Communications, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(926), "SchoolBoard Limited ");
    manufacturerIDStrings.put(Integer.valueOf(927), "Molex Corporation ");
    manufacturerIDStrings.put(Integer.valueOf(928), "IVT Wireless Limited");
    manufacturerIDStrings.put(Integer.valueOf(929), "Alpine Labs LLC");
    manufacturerIDStrings.put(Integer.valueOf(930), "Candura Instruments");
    manufacturerIDStrings.put(Integer.valueOf(931), "SmartMovt Technology Co., Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(932), "Token Zero Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(933), "ACE CAD Enterprise Co., Ltd. (ACECAD) ");
    manufacturerIDStrings.put(Integer.valueOf(934), "Medela, Inc ");
    manufacturerIDStrings.put(Integer.valueOf(935), "AeroScout ");
    manufacturerIDStrings.put(Integer.valueOf(936), "Esrille Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(937), "THINKERLY SRL ");
    manufacturerIDStrings.put(Integer.valueOf(938), "Exon Sp. z o.o. ");
    manufacturerIDStrings.put(Integer.valueOf(939), "Meizu Technology Co., Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(940), "Smablo LTD ");
    manufacturerIDStrings.put(Integer.valueOf(941), "XiQ ");
    manufacturerIDStrings.put(Integer.valueOf(942), "Allswell Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(943), "Comm-N-Sense Corp DBA Verigo ");
    manufacturerIDStrings.put(Integer.valueOf(944), "VIBRADORM GmbH ");
    manufacturerIDStrings.put(Integer.valueOf(945), "Otodata Wireless Network Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(946), "Propagation Systems Limited ");
    manufacturerIDStrings.put(Integer.valueOf(947), "Midwest Instruments & Controls ");
    manufacturerIDStrings.put(Integer.valueOf(948), "Alpha Nodus, inc. ");
    manufacturerIDStrings.put(Integer.valueOf(949), "petPOMM, Inc ");
    manufacturerIDStrings.put(Integer.valueOf(950), "Mattel ");
    manufacturerIDStrings.put(Integer.valueOf(951), "Airbly Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(952), "A-Safe Limited ");
    manufacturerIDStrings.put(Integer.valueOf(953), "FREDERIQUE CONSTANT SA ");
    manufacturerIDStrings.put(Integer.valueOf(954), "Maxscend Microelectronics Company Limited ");
    manufacturerIDStrings.put(Integer.valueOf(955), "Abbott Diabetes Care ");
    manufacturerIDStrings.put(Integer.valueOf(956), "ASB Bank Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(957), "amadas ");
    manufacturerIDStrings.put(Integer.valueOf(958), "Applied Science, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(959), "iLumi Solutions Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(960), "Arch Systems Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(961), "Ember Technologies, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(962), "Snapchat Inc");
    manufacturerIDStrings.put(Integer.valueOf(963), "Casambi Technologies Oy ");
    manufacturerIDStrings.put(Integer.valueOf(964), "Pico Technology Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(965), "St. Jude Medical, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(966), "Intricon ");
    manufacturerIDStrings.put(Integer.valueOf(967), "Structural Health Systems, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(968), "Avvel International ");
    manufacturerIDStrings.put(Integer.valueOf(969), "Gallagher Group ");
    manufacturerIDStrings.put(Integer.valueOf(970), "In2things Automation Pvt. Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(971), "SYSDEV Srl ");
    manufacturerIDStrings.put(Integer.valueOf(972), "Vonkil Technologies Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(973), "Wynd Technologies, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(974), "CONTRINEX S.A. ");
    manufacturerIDStrings.put(Integer.valueOf(975), "MIRA, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(976), "Watteam Ltd");
    manufacturerIDStrings.put(Integer.valueOf(977), "Density Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(978), "IOT Pot India Private Limited ");
    manufacturerIDStrings.put(Integer.valueOf(979), "Sigma Connectivity AB ");
    manufacturerIDStrings.put(Integer.valueOf(980), "PEG PEREGO SPA ");
    manufacturerIDStrings.put(Integer.valueOf(981), "Wyzelink Systems Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(982), "Yota Devices LTD ");
    manufacturerIDStrings.put(Integer.valueOf(983), "FINSECUR ");
    manufacturerIDStrings.put(Integer.valueOf(984), "Zen-Me Labs Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(985), "3IWare Co., Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(986), "EnOcean GmbH ");
    manufacturerIDStrings.put(Integer.valueOf(987), "Instabeat, Inc ");
    manufacturerIDStrings.put(Integer.valueOf(988), "Nima Labs ");
    manufacturerIDStrings.put(Integer.valueOf(989), "Andreas Stihl AG & Co. KG ");
    manufacturerIDStrings.put(Integer.valueOf(990), "Nathan Rhoades LLC ");
    manufacturerIDStrings.put(Integer.valueOf(991), "Grob Technologies, LLC ");
    manufacturerIDStrings.put(Integer.valueOf(992), "Actions (Zhuhai) Technology Co., Limited ");
    manufacturerIDStrings.put(Integer.valueOf(993), "SPD Development Company Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(994), "Sensoan Oy ");
    manufacturerIDStrings.put(Integer.valueOf(995), "Qualcomm Life Inc ");
    manufacturerIDStrings.put(Integer.valueOf(996), "Chip-ing AG ");
    manufacturerIDStrings.put(Integer.valueOf(997), "ffly4u ");
    manufacturerIDStrings.put(Integer.valueOf(998), "IoT Instruments Oy ");
    manufacturerIDStrings.put(Integer.valueOf(999), "TRUE Fitness Technology ");
    manufacturerIDStrings.put(Integer.valueOf(1000), "Reiner Kartengeraete GmbH & Co. KG. ");
    manufacturerIDStrings.put(Integer.valueOf(1001), "SHENZHEN LEMONJOY TECHNOLOGY CO., LTD. ");
    manufacturerIDStrings.put(Integer.valueOf(1002), "Hello Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1003), "Evollve Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1004), "Jigowatts Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1005), "BASIC MICRO.COM,INC. ");
    manufacturerIDStrings.put(Integer.valueOf(1006), "CUBE TECHNOLOGIES ");
    manufacturerIDStrings.put(Integer.valueOf(1007), "foolography GmbH ");
    manufacturerIDStrings.put(Integer.valueOf(1008), "CLINK ");
    manufacturerIDStrings.put(Integer.valueOf(1009), "Hestan Smart Cooking Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1010), "WindowMaster A/S ");
    manufacturerIDStrings.put(Integer.valueOf(1011), "Flowscape AB ");
    manufacturerIDStrings.put(Integer.valueOf(1012), "PAL Technologies Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(1013), "WHERE, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1014), "Iton Technology Corp. ");
    manufacturerIDStrings.put(Integer.valueOf(1015), "Owl Labs Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1016), "Rockford Corp. ");
    manufacturerIDStrings.put(Integer.valueOf(1017), "Becon Technologies Co.,Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(1018), "Vyassoft Technologies Inc ");
    manufacturerIDStrings.put(Integer.valueOf(1019), "Nox Medical ");
    manufacturerIDStrings.put(Integer.valueOf(1020), "Kimberly-Clark ");
    manufacturerIDStrings.put(Integer.valueOf(1021), "Trimble Navigation Ltd. ");
    manufacturerIDStrings.put(Integer.valueOf(1022), "Littelfuse ");
    manufacturerIDStrings.put(Integer.valueOf(1023), "Withings ");
    manufacturerIDStrings.put(Integer.valueOf(1024), "i-developer IT Beratung UG ");
    manufacturerIDStrings.put(Integer.valueOf(1025), "リレーションズ株式会社 ");
    manufacturerIDStrings.put(Integer.valueOf(1026), "Sears Holdings Corporation ");
    manufacturerIDStrings.put(Integer.valueOf(1027), "Gantner Electronic GmbH ");
    manufacturerIDStrings.put(Integer.valueOf(1028), "Authomate Inc ");
    manufacturerIDStrings.put(Integer.valueOf(1029), "Vertex International, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1030), "Airtago ");
    manufacturerIDStrings.put(Integer.valueOf(1031), "Swiss Audio SA ");
    manufacturerIDStrings.put(Integer.valueOf(1032), "ToGetHome Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1033), "AXIS ");
    manufacturerIDStrings.put(Integer.valueOf(1034), "Openmatics ");
    manufacturerIDStrings.put(Integer.valueOf(1035), "Jana Care Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1036), "Senix Corporation ");
    manufacturerIDStrings.put(Integer.valueOf(1037), "NorthStar Battery Company, LLC ");
    manufacturerIDStrings.put(Integer.valueOf(1038), "SKF (U.K.) Limited ");
    manufacturerIDStrings.put(Integer.valueOf(1039), "CO-AX Technology, Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1040), "Fender Musical Instruments ");
    manufacturerIDStrings.put(Integer.valueOf(1041), "Luidia Inc ");
    manufacturerIDStrings.put(Integer.valueOf(1042), "SEFAM ");
    manufacturerIDStrings.put(Integer.valueOf(1043), "Wireless Cables Inc ");
    manufacturerIDStrings.put(Integer.valueOf(1044), "Lightning Protection International Pty Ltd ");
    manufacturerIDStrings.put(Integer.valueOf(1045), "Uber Technologies Inc ");
    manufacturerIDStrings.put(Integer.valueOf(1046), "SODA GmbH ");
    manufacturerIDStrings.put(Integer.valueOf(1047), "Fatigue Science ");
    manufacturerIDStrings.put(Integer.valueOf(1048), "Alpine Electronics Inc. ");
    manufacturerIDStrings.put(Integer.valueOf(1049), "Novalogy LTD ");
    manufacturerIDStrings.put(Integer.valueOf(1050), "Friday Labs Limited ");
    manufacturerIDStrings.put(Integer.valueOf(1051), "OrthoAccel Technologies ");
  }
}


/* Location:              D:\classes-dex2jar.jar!\com\ti\ble\common\BluetoothGATTDefines.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */