create database getout;
use getout;

CREATE TABLE IF NOT EXISTS EDIFICIO(NOME VARCHAR(20) PRIMARY KEY);
CREATE TABLE IF NOT EXISTS PIANO(NOME VARCHAR(20) PRIMARY KEY, EDIFICIO VARCHAR(20) NOT NULL);
CREATE TABLE IF NOT EXISTS AULA(NOME VARCHAR(20) PRIMARY KEY, X FLOAT(4,2) NOT NULL, 
						Y FLOAT(4,2) NOT NULL, PIANO VARCHAR(20) NOT NULL);
                        
CREATE TABLE IF NOT EXISTS TRONCO(
                ID INTEGER(10) AUTO_INCREMENT PRIMARY KEY,
                X FLOAT(4,2) NOT NULL,
                Y FLOAT(4,2) NOT NULL,
                LARGHEZZA FLOAT(8,4) NOT NULL,
                PIANO VARCHAR(20) NOT NULL);
CREATE TABLE IF NOT EXISTS BEACON(
                ID VARCHAR(40) PRIMARY KEY,
                X FLOAT(4,2) NOT NULL,
                Y FLOAT(4,2) NOT NULL,
                TRONCO VARCHAR(20) NOT NULL);
                
                
CREATE TABLE MAPPA(IMMAGINE TEXT NOT NULL, PIANO VARCHAR(20) PRIMARY KEY);